version: '3'
services:
  db:
    image: library/postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    networks:
      - taskcore-backend-tier
    volumes:
      - taskcore-db:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  taskcore-db:
    driver: local
networks:
  taskcore-backend-tier:
    driver: bridge