import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "./context/SessionProvider";
import Loginlayout from "./LoginLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Provider to manage auth */}
        <SessionProvider>
          <Loginlayout>{children}</Loginlayout>
        </SessionProvider>
      </body>
    </html>
  );
}
