import "reflect-metadata";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "./context/SessionProvider";
import Loginlayout from "./LoginLayout";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={`${inter.className} h-full`}>
        {/* Provider to manage auth */}
        <NextUIProvider className="h-full">
          <SessionProvider>
            <Loginlayout>{children}</Loginlayout>
          </SessionProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
