import "reflect-metadata";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "./context/SessionProvider";
import Loginlayout from "./LoginLayout";
import { NextUIProvider } from "@nextui-org/react";
import { StoreProvider } from "@/presentation/components/atoms/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout
 * Funcion principal para renderizar la aplicacion
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={`${inter.className} h-full`}>
        {/* Provider to manage auth */}
        <StoreProvider>
          <NextUIProvider className="h-full">
            <SessionProvider>
              <Loginlayout>{children}</Loginlayout>
            </SessionProvider>
          </NextUIProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
